name: HardcoreGamesPlugin
version: '1.0.0'
main: br.dev.sno0s.hgplugin.Hgplugin
api-version: '26.2'

commands:
  startmatch:
    permission: hg.plugin.startmatch
  spawnfeast:
    permission: hg.plugin.spawnfeast
  kit: {}
  stats: {}
  restarthg:
    permission: hg.plugin.restarthg
  timeskip:
    permission: hg.plugin.timeskip

permissions:
  hg.plugin.startmatch:
    default: op
  hg.plugin.spawnfeast:
    default: op
  hg.plugin.restarthg:
    default: op
  hg.plugin.timeskip:
    default: op
